import itertools

from model import input_lvs

data = dict()
j = []
for value in input_lvs:
    data[value["name"]] = [t for t in value["terms"]]
    j.append(value["name"])


print(j)


value = {
    "Age": lambda x: 6 + x * -2,
    "Height": lambda x: 1 + -(1 ** (x + 1)),
    "Body type": lambda x: x * 3 - 1 * max(0, x - 1),
    "Income": lambda x: x * 3 - 1 * max(0, x - 1),
}


rez = []
rez2 = []
for tupl in tuple(itertools.product(*[data[i] for i in data])):
    t = 0
    for index, param in enumerate(data):
        t += value[param](data[param].index(tupl[index]))
    rez2.append(t)
    t2 = (tupl, "low")
    if t > 3:
        t2 = (tupl, "medium")
    if t > 5:
        t2 = (tupl, "high")

    rez.append(t2)


print(rez)


["Age", "Height", "Body type", "Income"]
[
    (("young", "short", "thin", "low"), "high"),
    (("young", "short", "thin", "medium"), "high"),
    (("young", "short", "thin", "high"), "high"),
    (("young", "short", "thin", "extremely high"), "high"),
    (("young", "short", "average", "low"), "high"),
    (("young", "short", "average", "medium"), "high"),
    (("young", "short", "average", "high"), "high"),
    (("young", "short", "average", "extremely high"), "high"),
    (("young", "short", "athletic", "low"), "high"),
    (("young", "short", "athletic", "medium"), "high"),
    (("young", "short", "athletic", "high"), "high"),
    (("young", "short", "athletic", "extremely high"), "high"),
    (("young", "short", "extra pound", "low"), "high"),
    (("young", "short", "extra pound", "medium"), "high"),
    (("young", "short", "extra pound", "high"), "high"),
    (("young", "short", "extra pound", "extremely high"), "high"),
    (("young", "average", "thin", "low"), "high"),
    (("young", "average", "thin", "medium"), "high"),
    (("young", "average", "thin", "high"), "high"),
    (("young", "average", "thin", "extremely high"), "high"),
    (("young", "average", "average", "low"), "high"),
    (("young", "average", "average", "medium"), "high"),
    (("young", "average", "average", "high"), "high"),
    (("young", "average", "average", "extremely high"), "high"),
    (("young", "average", "athletic", "low"), "high"),
    (("young", "average", "athletic", "medium"), "high"),
    (("young", "average", "athletic", "high"), "high"),
    (("young", "average", "athletic", "extremely high"), "high"),
    (("young", "average", "extra pound", "low"), "high"),
    (("young", "average", "extra pound", "medium"), "high"),
    (("young", "average", "extra pound", "high"), "high"),
    (("young", "average", "extra pound", "extremely high"), "high"),
    (("young", "tall", "thin", "low"), "high"),
    (("young", "tall", "thin", "medium"), "high"),
    (("young", "tall", "thin", "high"), "high"),
    (("young", "tall", "thin", "extremely high"), "high"),
    (("young", "tall", "average", "low"), "high"),
    (("young", "tall", "average", "medium"), "high"),
    (("young", "tall", "average", "high"), "high"),
    (("young", "tall", "average", "extremely high"), "high"),
    (("young", "tall", "athletic", "low"), "high"),
    (("young", "tall", "athletic", "medium"), "high"),
    (("young", "tall", "athletic", "high"), "high"),
    (("young", "tall", "athletic", "extremely high"), "high"),
    (("young", "tall", "extra pound", "low"), "high"),
    (("young", "tall", "extra pound", "medium"), "high"),
    (("young", "tall", "extra pound", "high"), "high"),
    (("young", "tall", "extra pound", "extremely high"), "high"),
    (("adult", "short", "thin", "low"), "medium"),
    (("adult", "short", "thin", "medium"), "high"),
    (("adult", "short", "thin", "high"), "high"),
    (("adult", "short", "thin", "extremely high"), "high"),
    (("adult", "short", "average", "low"), "high"),
    (("adult", "short", "average", "medium"), "high"),
    (("adult", "short", "average", "high"), "high"),
    (("adult", "short", "average", "extremely high"), "high"),
    (("adult", "short", "athletic", "low"), "high"),
    (("adult", "short", "athletic", "medium"), "high"),
    (("adult", "short", "athletic", "high"), "high"),
    (("adult", "short", "athletic", "extremely high"), "high"),
    (("adult", "short", "extra pound", "low"), "high"),
    (("adult", "short", "extra pound", "medium"), "high"),
    (("adult", "short", "extra pound", "high"), "high"),
    (("adult", "short", "extra pound", "extremely high"), "high"),
    (("adult", "average", "thin", "low"), "medium"),
    (("adult", "average", "thin", "medium"), "high"),
    (("adult", "average", "thin", "high"), "high"),
    (("adult", "average", "thin", "extremely high"), "high"),
    (("adult", "average", "average", "low"), "high"),
    (("adult", "average", "average", "medium"), "high"),
    (("adult", "average", "average", "high"), "high"),
    (("adult", "average", "average", "extremely high"), "high"),
    (("adult", "average", "athletic", "low"), "high"),
    (("adult", "average", "athletic", "medium"), "high"),
    (("adult", "average", "athletic", "high"), "high"),
    (("adult", "average", "athletic", "extremely high"), "high"),
    (("adult", "average", "extra pound", "low"), "high"),
    (("adult", "average", "extra pound", "medium"), "high"),
    (("adult", "average", "extra pound", "high"), "high"),
    (("adult", "average", "extra pound", "extremely high"), "high"),
    (("adult", "tall", "thin", "low"), "medium"),
    (("adult", "tall", "thin", "medium"), "high"),
    (("adult", "tall", "thin", "high"), "high"),
    (("adult", "tall", "thin", "extremely high"), "high"),
    (("adult", "tall", "average", "low"), "high"),
    (("adult", "tall", "average", "medium"), "high"),
    (("adult", "tall", "average", "high"), "high"),
    (("adult", "tall", "average", "extremely high"), "high"),
    (("adult", "tall", "athletic", "low"), "high"),
    (("adult", "tall", "athletic", "medium"), "high"),
    (("adult", "tall", "athletic", "high"), "high"),
    (("adult", "tall", "athletic", "extremely high"), "high"),
    (("adult", "tall", "extra pound", "low"), "high"),
    (("adult", "tall", "extra pound", "medium"), "high"),
    (("adult", "tall", "extra pound", "high"), "high"),
    (("adult", "tall", "extra pound", "extremely high"), "high"),
    (("middle age", "short", "thin", "low"), "low"),
    (("middle age", "short", "thin", "medium"), "medium"),
    (("middle age", "short", "thin", "high"), "high"),
    (("middle age", "short", "thin", "extremely high"), "high"),
    (("middle age", "short", "average", "low"), "medium"),
    (("middle age", "short", "average", "medium"), "high"),
    (("middle age", "short", "average", "high"), "high"),
    (("middle age", "short", "average", "extremely high"), "high"),
    (("middle age", "short", "athletic", "low"), "high"),
    (("middle age", "short", "athletic", "medium"), "high"),
    (("middle age", "short", "athletic", "high"), "high"),
    (("middle age", "short", "athletic", "extremely high"), "high"),
    (("middle age", "short", "extra pound", "low"), "high"),
    (("middle age", "short", "extra pound", "medium"), "high"),
    (("middle age", "short", "extra pound", "high"), "high"),
    (("middle age", "short", "extra pound", "extremely high"), "high"),
    (("middle age", "average", "thin", "low"), "low"),
    (("middle age", "average", "thin", "medium"), "medium"),
    (("middle age", "average", "thin", "high"), "high"),
    (("middle age", "average", "thin", "extremely high"), "high"),
    (("middle age", "average", "average", "low"), "medium"),
    (("middle age", "average", "average", "medium"), "high"),
    (("middle age", "average", "average", "high"), "high"),
    (("middle age", "average", "average", "extremely high"), "high"),
    (("middle age", "average", "athletic", "low"), "high"),
    (("middle age", "average", "athletic", "medium"), "high"),
    (("middle age", "average", "athletic", "high"), "high"),
    (("middle age", "average", "athletic", "extremely high"), "high"),
    (("middle age", "average", "extra pound", "low"), "high"),
    (("middle age", "average", "extra pound", "medium"), "high"),
    (("middle age", "average", "extra pound", "high"), "high"),
    (("middle age", "average", "extra pound", "extremely high"), "high"),
    (("middle age", "tall", "thin", "low"), "low"),
    (("middle age", "tall", "thin", "medium"), "medium"),
    (("middle age", "tall", "thin", "high"), "high"),
    (("middle age", "tall", "thin", "extremely high"), "high"),
    (("middle age", "tall", "average", "low"), "medium"),
    (("middle age", "tall", "average", "medium"), "high"),
    (("middle age", "tall", "average", "high"), "high"),
    (("middle age", "tall", "average", "extremely high"), "high"),
    (("middle age", "tall", "athletic", "low"), "high"),
    (("middle age", "tall", "athletic", "medium"), "high"),
    (("middle age", "tall", "athletic", "high"), "high"),
    (("middle age", "tall", "athletic", "extremely high"), "high"),
    (("middle age", "tall", "extra pound", "low"), "high"),
    (("middle age", "tall", "extra pound", "medium"), "high"),
    (("middle age", "tall", "extra pound", "high"), "high"),
    (("middle age", "tall", "extra pound", "extremely high"), "high"),
    (("old", "short", "thin", "low"), "low"),
    (("old", "short", "thin", "medium"), "low"),
    (("old", "short", "thin", "high"), "medium"),
    (("old", "short", "thin", "extremely high"), "high"),
    (("old", "short", "average", "low"), "low"),
    (("old", "short", "average", "medium"), "high"),
    (("old", "short", "average", "high"), "high"),
    (("old", "short", "average", "extremely high"), "high"),
    (("old", "short", "athletic", "low"), "medium"),
    (("old", "short", "athletic", "medium"), "high"),
    (("old", "short", "athletic", "high"), "high"),
    (("old", "short", "athletic", "extremely high"), "high"),
    (("old", "short", "extra pound", "low"), "high"),
    (("old", "short", "extra pound", "medium"), "high"),
    (("old", "short", "extra pound", "high"), "high"),
    (("old", "short", "extra pound", "extremely high"), "high"),
    (("old", "average", "thin", "low"), "low"),
    (("old", "average", "thin", "medium"), "low"),
    (("old", "average", "thin", "high"), "medium"),
    (("old", "average", "thin", "extremely high"), "high"),
    (("old", "average", "average", "low"), "low"),
    (("old", "average", "average", "medium"), "high"),
    (("old", "average", "average", "high"), "high"),
    (("old", "average", "average", "extremely high"), "high"),
    (("old", "average", "athletic", "low"), "medium"),
    (("old", "average", "athletic", "medium"), "high"),
    (("old", "average", "athletic", "high"), "high"),
    (("old", "average", "athletic", "extremely high"), "high"),
    (("old", "average", "extra pound", "low"), "high"),
    (("old", "average", "extra pound", "medium"), "high"),
    (("old", "average", "extra pound", "high"), "high"),
    (("old", "average", "extra pound", "extremely high"), "high"),
    (("old", "tall", "thin", "low"), "low"),
    (("old", "tall", "thin", "medium"), "low"),
    (("old", "tall", "thin", "high"), "medium"),
    (("old", "tall", "thin", "extremely high"), "high"),
    (("old", "tall", "average", "low"), "low"),
    (("old", "tall", "average", "medium"), "high"),
    (("old", "tall", "average", "high"), "high"),
    (("old", "tall", "average", "extremely high"), "high"),
    (("old", "tall", "athletic", "low"), "medium"),
    (("old", "tall", "athletic", "medium"), "high"),
    (("old", "tall", "athletic", "high"), "high"),
    (("old", "tall", "athletic", "extremely high"), "high"),
    (("old", "tall", "extra pound", "low"), "high"),
    (("old", "tall", "extra pound", "medium"), "high"),
    (("old", "tall", "extra pound", "high"), "high"),
    (("old", "tall", "extra pound", "extremely high"), "high"),
]
